### ISSUE TITLE
new version with 1.07 support breaks online mode.

### ISSUE THREAD

**Issue by apoklyps3** [pes-modding/sider6#2]
failing to connect to opponent ever since the latest version of sider.
worked flawelessly in the previous version. no mod added since.

**Comment by juce** [comment]
that isn't because of sider, but because of database files that you have - as part of a mod (like evo-web patch, for example). Try without any mods - just with that comes with default sider: unzip the archive into desktop, run sider.exe.

**Comment by apoklyps3** [comment]
ok. thanks. 
so stupid of me :(

**Comment by juce** [comment]
no worries.
closing this one
